### ISSUE TITLE
Call for usage information

### ISSUE THREAD

**Issue by otembajelle** [wimjongman/pipolos#4]
Thanks for creating Pipolos. It works very well on my R-Pi.

In the distribution there is a directory "load" that appears to offer permanent installation of my bundles. It contains a readme.txt "This is a convenience directory created for the Felix fileinstall bundle."

I tried it out on my workstation but my bundles would not auto start. So my questions are ...
- What is the preferred way to install my bundles permanently in a Pipolos environment?
- Is there a way to install my bundles permanently via the Felix web console?

**Comment by wimjongman** [comment]
There are many ways of permanently installing bundles. 
- The first one is to put bundles in the load directory. The fileinstall bundle will poll this directory and will install and uninstall bundles when they are added and removed from that directory. However, for this to work, you have to start the fileinstall bundle first. I believe it is not started automagically. (edit: I have changed the build so that fileinstall is automatically started). Equinox will remember that you have started fileinstall once and will restart it again on subsequent starts of the framework. All this information is removed when you start with the -clean option. 
- You can also make your own build. This repository is using Tycho to build. Just examine the pom.xml files in this repository and you should able to figure out how this works. Also see the [product file](https://github.com/wimjongman/pipolos/blob/master/com.weltevree.pipolos.product/polos.product) to examine what is put into the product. 
- Other ways of adding bundles would be to put them in the plugins directory and changing the config.ini file in the configuration directory.

**Comment by otembajelle** [comment]
> > you have to start the fileinstall bundle first
> > thx, I did not notice
